In [5]:
import torch

In [6]:
torch.manual_seed(1)

In [7]:
x=torch.zeros(2,3)
for i in range(2):
    for j in range(3):
        x[i,j] = j

In [8]:
y=torch.zeros(2,3)
for i in range(2):
    for j in range(3):
        y[i,j] = j

In [9]:
w0 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w0[i,j] = j
w0 = torch.nn.Parameter(w0)

In [10]:
x

tensor([[0., 1., 2.],
        [0., 1., 2.]])

In [11]:
w1 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w1[i,j] = j
w1 = torch.nn.Parameter(w1)

w2 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w2[i,j] = j
w2 = torch.nn.Parameter(w2)

w3 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w3[i,j] = j + 2
w3 = torch.nn.Parameter(w3)

In [12]:
l1=None
l2=None

In [13]:
g = w3
adv1 = w1
adv2 = w2

In [14]:
sgd = torch.optim.SGD((g,adv1,adv2), lr=0.5)

In [15]:
print(g)
print(adv1)
print(adv2)

Parameter containing:
tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]], requires_grad=True)
Parameter containing:
tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]], requires_grad=True)
Parameter containing:
tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]], requires_grad=True)


# Compute grads for generator 

In [16]:
print(g.grad)
print(adv1.grad)

None
None


In [17]:
sgd.zero_grad()

In [18]:
print(g.grad)
print(adv1.grad)

None
None


---

In [19]:
adv1.requires_grad=False

---

In [20]:
tmp = x.matmul(w3) 
l1 = tmp.matmul(w1).sum()

In [21]:
print(g.grad)
print(adv1.grad)

None
None


In [22]:
#adv1.grad.data.zero_()

In [23]:
print(g.grad)
print(adv1.grad)

None
None


# Compute grads for discriminator

In [24]:
w1.requires_grad=True

In [25]:
tmp2=tmp.detach() 
l2 = tmp2.matmul(w1).sum() # might be differnet from l1

In [26]:
l3 = l1+l2
l3.backward()

In [27]:
print(g.grad)
print(adv1.grad)

tensor([[ 0.,  0.,  0.],
        [ 6.,  6.,  6.],
        [12., 12., 12.]])
tensor([[12., 12., 12.],
        [18., 18., 18.],
        [24., 24., 24.]])


In [28]:
print(g.grad)
print(adv1.grad)

tensor([[ 0.,  0.,  0.],
        [ 6.,  6.,  6.],
        [12., 12., 12.]])
tensor([[12., 12., 12.],
        [18., 18., 18.],
        [24., 24., 24.]])


In [45]:
l1.grad_fn.next_functions[0][0].next_functions[0][0]

In [ ]:
sgd.step()

In [ ]:
print(g)
print(adv1)
print(adv2)