In [3]:
torch.manual_seed(1)

In [1]:
import torch

In [70]:
x=torch.zeros(2,3)
for i in range(2):
    for j in range(3):
        x[i,j] = j

In [79]:
y=torch.zeros(2,3)
for i in range(2):
    for j in range(3):
        y[i,j] = j

In [80]:
w0 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w0[i,j] = j
w0 = torch.nn.Parameter(w0)

In [81]:
x

tensor([[0., 1., 2.],
        [0., 1., 2.]])

In [82]:
w1 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w1[i,j] = j
w1 = torch.nn.Parameter(w1)

w2 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w2[i,j] = j + 1
w2 = torch.nn.Parameter(w2)

w3 = torch.ones(3,3)
for i in range(3):
    for j in range(3):
        w3[i,j] = j + 2
w3 = torch.nn.Parameter(w3)

In [83]:
l1 = x.matmul(w1).sum()
l2 = x.matmul(w2).sum()

In [84]:
print(w1.grad)
print(w2.grad)

None
None


In [75]:
l1.backward(retain_graph=True)
l2.backward(retain_graph=True)

In [76]:
print(w1.grad)
print(w2.grad)

tensor([[0., 0., 0.],
        [2., 2., 2.],
        [4., 4., 4.]])
tensor([[0., 0., 0.],
        [2., 2., 2.],
        [4., 4., 4.]])


In [90]:
l3 = y.matmul(w0).matmu.sum()

In [91]:
(l1+l2+l3).backward()

In [92]:
print(w1.grad)
print(w2.grad)
print(w3.grad)
print(w0.grad)

tensor([[0., 0., 0.],
        [2., 2., 2.],
        [4., 4., 4.]])
tensor([[0., 0., 0.],
        [2., 2., 2.],
        [4., 4., 4.]])
None
tensor([[0., 0., 0.],
        [2., 2., 2.],
        [4., 4., 4.]])
